### ISSUE TITLE
clarify the meaning of a views and DesignFormat in the architectural overview

### ISSUE THREAD

**Issue by maliberty** [efabless/openlane2#485]
### Description

It is confusing that in https://openlane2.readthedocs.io/en/latest/reference/architecture.html
```
States
A openlane.steps.State is a snapshot of paths to views at any point in time, in dictionary form.
Keys must be of the type openlane.steps.DesignFormat
```
mentions views without ever defining what a view is.  Likewise DesignFormat.

### Proposal

Define views and DesignFormat before using those terms.  Also those terms are not links in the docs while other terms are.

**Comment by donn** [comment]
I *think* they used to be terms but broke when I created a dedicated submodule for state-- will have to track down why it didn't warn about that

**Comment by donn** [comment]
Fixed in `dev`: https://openlane2.readthedocs.io/en/dev/reference/architecture.html

**Comment by maliberty** [comment]
This is a circular definition:
```
class openlane.state.DesignFormat(value)
A list of design formats that may be kept in the state object.
```
I still don't know what it is.  The parameters have no doc string so they aren't clear either.

**Comment by maliberty** [comment]
Its also confusing that it is described as a list but seems to be a singular object.
